CREATE TABLE T_OFFICES(
	OFFC_ID INT NOT NULL,
	OFFC_COUNTRY VARCHAR(30) NOT NULL,
    OFFC_DESCRIPTION VARCHAR(80) NOT NULL,
    OFFC_NAME VARCHAR(30)
);
DROP TABLE T_OFFICES;
-- HOLA ESTO ES UN COMENT --
CREATE TABLE T_OFFICES(
	OFFC_ID INT NOT NULL,
	OFFC_COUNTRY VARCHAR(30) NOT NULL,
    OFFC_DESCRIPTION VARCHAR(90) NOT NULL,
    OFFC_NAME VARCHAR(30)
);


-- Eliminar el campo OFFC_NAME --
ALTER TABLE T_OFFICES DROP COLUMN OFFC_NAME;
-- Agregar campo OFF_CITY despues de OFF_COUNTRY
ALTER TABLE T_OFFICES ADD COLUMN OFFC_CITY VARCHAR(50) 
NOT NULL AFTER OFFC_COUNTRY;
-- Modificar campo --
ALTER TABLE T_OFFICES MODIFY COLUMN OFFC_DESCRIPTION VARCHAR(100);