ALTER TABLE `T_OFFICES` ADD PRIMARY KEY (`OFFC_ID`);

CREATE TABLE `T_EMPLOYEES` (
  `EMPL_ID` INT NOT NULL AUTO_INCREMENT,
  `OFFC_ID` INT NOT NULL,
  `KNLN_ID` INT,
  `EMPL_FORNAME` VARCHAR(50) NOT NULL,
  `EMPL_MIDDLE_NAME` VARCHAR(50),
  `EMPL_SURNAME` VARCHAR(50) NOT NULL,
  `EMPL_NUMBER` INT NOT NULL,
  `EMPL_HIRE_DATE` DATETIME NOT NULL,
  `EMPL_MENTOR_ID` INT,
  PRIMARY KEY (`EMPL_ID`));
  
INSERT INTO T_EMPLOYEES(
  `OFFC_ID`,
  `KNLN_ID`,
  `EMPL_FORNAME`,
  `EMPL_MIDDLE_NAME`,
  `EMPL_SURNAME`,
  `EMPL_NUMBER`,
  `EMPL_HIRE_DATE`,
  `EMPL_MENTOR_ID`
)
VALUES(
	10,
    10,
    'Albert',
    'David',
    'Gomes',
    '67',
    '2009-09-09',
    NULL
);

INSERT INTO T_EMPLOYEES(
  `OFFC_ID`,
  `KNLN_ID`,
  `EMPL_FORNAME`,
  `EMPL_MIDDLE_NAME`,
  `EMPL_SURNAME`,
  `EMPL_NUMBER`,
  `EMPL_HIRE_DATE`,
  `EMPL_MENTOR_ID`
)
VALUES(
	11,
    11,
    'Juan',
    'Pedro',
    'Sanz',
    '617',
    '2010-09-09',
    NULL
);
