SELECT e.EMPL_FORNAME, e.EMPL_SURNAME, o.OFFC_CITY, k.KNLN_NAME
FROM t_employees e 
INNER JOIN t_offices o ON 
	e.OFFC_ID = o.OFFC_ID
LEFT OUTER JOIN t_knowledge_lines k ON
	e.KNLN_ID = k.KNLN_ID
WHERE o.OFFC_COUNTRY IN ('España', 'Chile')
AND e.EMPL_MENTOR_ID is NULL;
	
CREATE VIEW V_PROJECTS_EMPLOYEES 
(NOMBRE, APELLIDOS, NUM_EMPLEADO, NOM_PROJT, CODI_PRJT)
AS
SELECT e.EMPL_FORNAME, e.EMPL_SURNAME, e.EMPL_NUMBER, p.PRJT_NAME, p.PRJT_CODE
FROM t_employees e 
INNER JOIN t_projects_employees pe ON 
	e.EMPL_ID = pe.EMPL_ID
INNER JOIN t_projects p ON
	pe.PRJT_ID = p.PRJT_ID;
	