SELECT CONCAT(e.EMPL_FORNAME, " ", e.EMPL_SURNAME) AS FULL_NAME, COUNT(d.DOCS_ID) AS NUM_DOCS
FROM t_employees e, t_documents d
WHERE e.EMPL_ID = d.EMPL_ID
GROUP BY e.EMPL_ID;

-- Equivalente al anterior
SELECT CONCAT(e.EMPL_FORNAME, " ", e.EMPL_SURNAME) FULL_NAME,
COUNT(d.DOCS_ID) NUM_DOCS
FROM t_employees e
INNER JOIN t_documents d 
ON e.EMPL_ID = d.EMPL_ID 
GROUP BY e.EMPL_ID
ORDER BY NUM_DOCS
LIMIT 1,2;


SELECT CONCAT(e.EMPL_FORNAME, " ", e.EMPL_SURNAME) FULL_NAME,
COUNT(d.DOCS_ID) NUM_DOCS
FROM t_employees e
LEFT OUTER JOIN t_documents d 
ON e.EMPL_ID = d.EMPL_ID 
GROUP BY e.EMPL_ID;