CREATE TABLE PROVEEDORES(
	PROV_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	PROV_NOM VARCHAR(50) NOT NULL,
	PRIMARY KEY (PROV_ID)
);

CREATE TABLE PIEZAS(
	PIEZ_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	PIEZ_NOM VARCHAR(100) NOT NULL,
	PRIMARY KEY (PIEZ_ID)
);

CREATE TABLE PRECIOS(
	PREC_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	PROV_ID INT UNSIGNED NOT NULL,
	PIEZ_ID INT UNSIGNED NOT NULL,
	PRIMARY KEY (PREC_ID)
);

